// M6/deliveroo/wms-frontend/src/app/auth/login.component.ts
import { Component, effect, ElementRef, inject, signal, viewChild, WritableSignal } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { AuthService } from './auth.service';
import { ForgotPasswordComponent } from './forgot-password/forgot-password.component';
import { Heading2Component, Heading4Component } from '../ui-library/Typography/Typography.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, ForgotPasswordComponent, Heading2Component, Heading4Component],
  template: `
    <div class="relative min-h-screen">
      <video
        #videoPlayer
        class="absolute top-0 left-0 z-0 h-full w-full object-cover"
        autoplay
        loop
        muted
        playsinline
      >
        <source src="https://xcivjcecfkgbhoojwovd.supabase.co/storage/v1/object/sign/misc/deliveroo-background.mp4?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wY2VlYTllZC02M2IxLTQwNTMtOGY2ZS04NzBiYjE3YWNjZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtaXNjL2RlbGl2ZXJvby1iYWNrZ3JvdW5kLm1wNCIsImlhdCI6MTc3OTU2ODI3NCwiZXhwIjoxODExMTA0Mjc0fQ.HPYw0tHg1Z8_lQpMx06OPuuiYFIQDB13w0jv-zHsJPY" type="video/mp4" />
      </video>
      <div class="absolute inset-0 bg-black/75"></div>
      <div class="relative z-10 flex min-h-screen items-center justify-center p-4">
        @if (showForgotPassword()) {
          <div
            class="w-full max-w-md rounded-xl border border-white/10 bg-blue-950/50 p-8 text-white shadow-2xl backdrop-blur-lg"
          >
            <app-forgot-password (backToLogin)="showForgotPassword.set(false)"></app-forgot-password>
          </div>
        } @else {
          <div
            class="w-full max-w-md space-y-8 rounded-xl border border-white/10 bg-blue-950/50 p-8 text-white shadow-2xl backdrop-blur-lg"
          >
            <div class="text-center">
              <img src="assets/deliveroo-logo.png" alt="Deliveroo Logo" class="mx-auto mb-4 h-24" />
              <ui-heading2>Warehouse Management System</ui-heading2>
              <p class="mt-2">Sign in to your account</p>
            </div>

            <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
              <div class="space-y-6">
                <div>
                  <label for="username" class="block text-sm font-medium"> Username </label>
                  <input
                    id="username"
                    name="username"
                    type="text"
                    formControlName="username"
                    class="input mt-1"
                    placeholder="Enter your username"
                  />
                  @if (loginForm.get('username')?.invalid && loginForm.get('username')?.touched) {
                    <div class="mt-1 text-sm text-error-400">Username is required</div>
                  }
                </div>

                <div>
                  <label for="password" class="block text-sm font-medium"> Password </label>
                  <input
                    id="password"
                    name="password"
                    type="password"
                    formControlName="password"
                    class="input mt-1"
                    placeholder="Enter your password"
                  />
                  @if (loginForm.get('password')?.invalid && loginForm.get('password')?.touched) {
                    <div class="mt-1 text-sm text-error-400">Password is required</div>
                  }
                </div>

                <div class="flex items-center justify-between">
                  <div class="flex items-center">
                    <input
                      id="remember-me"
                      name="remember-me"
                      type="checkbox"
                      formControlName="rememberMe"
                      class="h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                    />
                    <label for="remember-me" class="ml-2 block text-sm"> Remember me </label>
                  </div>
                  <div class="text-sm">
                    <a
                      (click)="showForgotPassword.set(true)"
                      class="cursor-pointer font-medium text-primary-400 hover:text-primary-300"
                    >
                      Forgot your password?
                    </a>
                  </div>
                </div>

                @if (error()) {
                  <div class="text-center text-sm text-error-400">
                    {{ error() }}
                  </div>
                }

                <button type="submit" [disabled]="loginForm.invalid || loading()" class="btn btn-primary w-full">
                  @if (loading()) {
                    <span class="mr-2 inline-block h-4 w-4 animate-spin">
                      <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                        <path
                          class="opacity-75"
                          fill="currentColor"
                          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                        ></path>
                      </svg>
                    </span>
                  }
                  {{ loading() ? 'Signing in...' : 'Sign in' }}
                </button>
              </div>
            </form>

            <div class="mt-6 rounded-lg bg-black/20 p-4">
              <ui-heading4 class="mb-2">Demo Credentials:</ui-heading4>
              <div class="space-y-1 text-xs">
                <div><strong>Manager:</strong> manager / password</div>
                <div><strong>Coordinator:</strong> coordinator / password</div>
                <div><strong>Worker:</strong> worker / password</div>
              </div>
            </div>
          </div>
        }
      </div>
    </div>
  `,
})
export class LoginComponent {
  loginForm: FormGroup;
  loading: WritableSignal<boolean> = signal(false);
  error: WritableSignal<string> = signal('');
  showForgotPassword: WritableSignal<boolean> = signal(false);
  videoPlayer = viewChild<ElementRef<HTMLVideoElement>>('videoPlayer');

  private formBuilder = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  constructor() {
    this.loginForm = this.formBuilder.group({
      username: ['', Validators.required],
      password: ['', Validators.required],
      rememberMe: [false]
    });

    effect(() => {
      const player = this.videoPlayer();
      if (player) {
        const videoElement = player.nativeElement;
        videoElement.muted = true;
        const playPromise = videoElement.play();
        if (playPromise !== undefined) {
          playPromise.catch(error => {
            console.error('Autoplay was prevented by the browser policy. This is expected behavior on some browsers and cannot be bypassed without user interaction.', error);
          });
        }
      }
    });
  }

  onSubmit(): void {
    if (this.loginForm.invalid) {
      return;
    }

    this.loading.set(true);
    this.error.set('');

    this.authService.login(this.loginForm.value).subscribe({
      next: () => {
        const returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/dashboard';
        this.router.navigate([returnUrl]);
      },
      error: (error) => {
        this.error.set(error.message || 'Login failed. Please try again.');
        this.loading.set(false);
      }
    });
  }
}

// M6/deliveroo/tms-frontend/src/pages/Login.tsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";

const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLogging, setIsLogging] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLogging(true);

    try {
      const success = await login(email, password);
      if (success) {
        toast({
          title: "Welcome back!",
          description: "You have successfully logged in.",
        });
        navigate("/dashboard");
      }
    } catch (error) {
      toast({
        title: "Login failed",
        description: "Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLogging(false);
    }
  };

  return (
    <div className="relative min-h-screen overflow-hidden">
      <video
        autoPlay
        loop
        muted
        playsInline
        className="absolute top-0 left-0 w-full h-full object-cover z-0 opacity-50"
      >
        <source
          src="https://xcivjcecfkgbhoojwovd.supabase.co/storage/v1/object/sign/misc/deliveroo-background.mp4?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wY2VlYTllZC02M2IxLTQwNTMtOGY2ZS04NzBiYjE3YWNjZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtaXNjL2RlbGl2ZXJvby1iYWNrZ3JvdW5kLm1wNCIsImlhdCI6MTc3OTU2ODI3NCwiZXhwIjoxODExMTA0Mjc0fQ.HPYw0tHg1Z8_lQpMx06OPuuiYFIQDB13w0jv-zHsJPY"
          type="video/mp4"
        />
      </video>
      <div className="relative z-10 flex min-h-screen items-center justify-center bg-black/20 p-4">
        <div className="w-full max-w-xl">
          <Card className="shadow-2xl rounded-2xl border-white/20 bg-white/10 backdrop-blur-lg">
            <CardHeader className="text-center">
              <div className="text-center">
                <img
                  src="/deliveroo-logo.png"
                  alt="Deliveroo Logo"
                  className="w-48 mx-auto"
                />
              </div>
              <CardTitle className="text-3xl font-semibold text-white">
                Transportation Management System
              </CardTitle>
              <CardDescription className="pt-2 text-gray-300">
                Sign in to access your logistics dashboard
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                  <Input
                    type="email"
                    placeholder="Email address"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                    className="h-12 rounded-lg border-white/30 bg-white/20 text-white placeholder:text-gray-300"
                  />
                </div>
                <div>
                  <Input
                    type="password"
                    placeholder="Password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    required
                    className="h-12 rounded-lg border-white/30 bg-white/20 text-white placeholder:text-gray-300"
                  />
                </div>
                <Button
                  type="submit"
                  className="h-12 w-full rounded-lg bg-blue-600 text-lg hover:bg-blue-700"
                  disabled={isLogging}
                >
                  {isLogging ? "Signing in..." : "Sign In"}
                </Button>
              </form>
              <div className="mt-6 text-center text-sm text-gray-300">
                <p>Demo: Use any email and password to login</p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default Login;
